language: node_js
node_js:
  - 6

branches:
  only:
    - master
    - dev

sudo: false

install:
  - npm install riot && npm i

cache:
  directories:
    - node_modules

notifications:
    email: false